### PR TITLE
Air: fix hot reload

### LINKED ISSUE #784: Race condition causes builds to cancel themselves when triggered during active build
# Description

When a file change triggers a build while an existing build is running, a race condition in `engine.go` causes the new build to cancel itself, making the running binary outdated.

# Root cause

You make a change to trigger build A. In the `buildRun()` function, build A will put `true` onto `buildRunCh`, and then proceed with its build. While it is building, you make a change to trigger build B. In the `start()` function, build B sees that there is a value on `buildRunCh`, so it puts a value onto `buildRunStopCh`:

```go
// already build and run now
select {
case <-e.buildRunCh:
  e.buildRunStopCh <- true
default:
}
```

In then calls `go buildRun()`. Since `buildRunCh` is now empty, it will be able to place `true` onto it. Directly after, it will see that `buildRunStopCh` is not-empty, and will **effectively cancel itself.**

```go
select {
case <-e.buildRunStopCh:
  return
default:
}
```

# Reproduction

Place the following in your `.air.toml` file to make the build process take a while. Make a change, wait a little bit (less than 10 seconds), and then make another change - the second one will not be reflected in the running code.

```toml
cmd = "echo 'Build started at' $(date +%H:%M:%S) && go build -o ./tmp/main . && echo 'Build complete' && sleep 10"
```

### PR DESCRIPTION
**Pull request by assembled-dylan**
## Description

Fixes an issue where later builds would cancel themselves if an earlier build was running. Now, if an earlier build A is running and a later build B begins, we will do the following:

1. Signal build A to stop via a `shouldCancelBuild` flag
2. Wait for build A to completely exit the `buildRun()` function by trying to acquire a mutex
3. Set `shouldCancelBuild` to false and proceed with build B

## Testing

Build binary locally and moved it to my remote machine, replacing the existing `air` binary for my user:

```zsh
$ GOOS=linux GOARCH=amd64 go build -o air-linux-amd64 .
$ tsh scp air-linux-amd64 dev-1.gokome.com:~/golang/bin/air
```

Then, ran remote dev and made two back-to-back saves triggering back-to-back builds. Added some logging and verified that the first build was canceled when the second build was triggered:

```
gocode/webserver/handlers_health.go has changed
stopping current build
waiting for current build to finish
starting new build
building...
gocode/webserver/handlers_health.go has changed
stopping current build
waiting for current build to finish
build canceled <- this indicates that the first build was canceled
starting new build
building...
running...
```

I made changes to the response in the `/api/health` endpoint during this process, and verified that the updates from the second save were reflected by hitting `localhost:3000/api/health`.

Also added a unit test to verify this functionality. I verified that the unit test failed before this change, but now passes.

## References

This attempts to fix https://github.com/air-verse/air/issues/784. The repo is not actively maintained, so forking seems like our best bet at this point.

### CODE REVIEW

**Review by cdkini — APPROVED** [review]
Could we add reference to https://github.com/air-verse/air/issues/784 either in the PR or in the code?

My preference would be to have the change be made there rather than forking (but obviously that's less in our control). Thanks for this!

File: runner/engine.go [hunk 1]
```diff
@@ -362,31 +364,31 @@ func (e *Engine) start() {
...
 
-		// already build and run now
-		select {
-		case <-e.buildRunCh:
-			e.buildRunStopCh <- true
-		default:
-		}
+		go func() {
+			// if current app is running, stop it
+			e.stopBin()
```
Comment (jaysunmah) [inline runner/engine.go:369]: is it intentional to call this outside of the main thread, and inside this goroutine now? (previously I think it was ran in the main thread?)

**Review by jaysunmah — APPROVED** [review]

File: runner/engine.go (hunk 1 above)
Comment (assembled-dylan) [reply runner/engine.go:369]: It seems like this is better, since `e.stopBin()` can block for up to five seconds, which would block file changes from being processed in the main loop of the `start()` function
